[tool.ruff]
target-version = "py312"
line-length    = 100
exclude = [
    "__pypackages__",
    ".venv",
    "build",
    "dist",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "B",   # bugbear
    "UP",  # pyupgrade
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "stability_monitor.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]