# Generated by Django 5.2.4 on 2025-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="port",
            field=models.IntegerField(default=8080),
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="ip",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
