name: CI

on:
  push:
    branches: [ main, chore/**, feat/** ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        env:
          MYSQL_DATABASE: stability_monitor
          MYSQL_ROOT_PASSWORD: root
        ports: [3306:3306]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7
        ports: [6379:6379]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..20}; do
            mysqladmin ping -h 127.0.0.1 -uroot -proot && break
            sleep 3
          done

      - name: Run migrations
        env:
          DJANGO_SECRET_KEY: dummy-key
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: stability_monitor
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: python manage.py migrate

      - name: Ruff lint & format check
        run: ruff check .

      - name: mypy type-check
        run: mypy .

      - name: Run tests
        env:
          DJANGO_SECRET_KEY: dummy-key
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: stability_monitor
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: pytest --cov --cov-report=term-missing

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .coverage
